-- Clauses that were silently dropped: session flags, CTE search/cycle,
-- trigger/view/index modifiers, function options, literals
SET LOCAL work_mem TO '128kB';

SELECT
	*
FROM
	ONLY parent_tbl;

UPDATE ONLY parent_tbl
SET
	x = 1;

DELETE FROM ONLY parent_tbl
WHERE
	x = 0;

WITH RECURSIVE 
graph(f, t) AS (
	SELECT
		1,
		2
	UNION ALL
	SELECT
		g.f,
		g.t
	FROM
		graph AS g
) SEARCH DEPTH FIRST BY f, t SET seq
SELECT
	*
FROM
	graph;

WITH RECURSIVE 
graph(f, t) AS (
	SELECT
		1,
		2
	UNION ALL
	SELECT
		g.f,
		g.t
	FROM
		graph AS g
) CYCLE f, t SET is_cycle TO true DEFAULT false USING path
SELECT
	*
FROM
	graph;

CREATE OR REPLACE TRIGGER my_trig
AFTER UPDATE OF a, b ON tbl
REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows
FOR EACH STATEMENT
EXECUTE FUNCTION f();

CREATE TEMPORARY VIEW tv WITH (security_barrier = true) AS
SELECT
	1;

CREATE VIEW cv (renamed_col) AS
SELECT
	1;

REINDEX (CONCURRENTLY, TABLESPACE fast) TABLE big_tbl;

CREATE TEMPORARY TABLE ctas_cols (ii, jj) USING heap AS
SELECT
	1,
	2
WITH NO DATA;

CREATE TEMPORARY SEQUENCE tseq;

CREATE TABLE compressed (
	f1 text COMPRESSION pglz,
	f2 text STORAGE EXTERNAL
);

CREATE TABLE opt_str (
	i int
) WITH (toast.autovacuum_enabled = false, autovacuum_analyze_scale_factor = 0.2);

CREATE INDEX ON ONLY parted_tbl USING btree (a);

CREATE INDEX ON vectors USING gist (v tsvector_ops (siglen = 100));

CREATE TABLE dflt (
	a int PRIMARY KEY USING INDEX TABLESPACE fast
);

CREATE TABLE ident_opts (
	id int GENERATED BY DEFAULT AS IDENTITY (START WITH 7 INCREMENT BY 5)
);

ALTER TYPE comp
	ALTER ATTRIBUTE r TYPE varchar;

ALTER TABLE t
	DROP COLUMN c CASCADE;

CREATE FUNCTION opts(IN a int, OUT b int)
RETURNS int
LANGUAGE sql
WINDOW
LEAKPROOF
COST 500
SET search_path TO 'pg_catalog'
AS $$
	SELECT
		a
$$;

DROP FUNCTION opts(IN a int, OUT b int);

SELECT
	date '2020-01-01',
	point '1,2',
	interval '1 day';

SELECT
	(matrix[1])[2]
FROM
	grids;

